controller_list:
  - name: fake_first_manipulator_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_second_manipulator_controller
    joints:
      - my_joint_s2
      - my_joint_l2
      - my_joint_e2
      - my_joint_u2
      - my_joint_r2
      - my_joint_b2
      - my_joint_t2
  - name: fake_dual_manipulator_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - my_joint_s2
      - my_joint_l2
      - my_joint_e2
      - my_joint_u2
      - my_joint_r2
      - my_joint_b2
      - my_joint_t2