# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: false
    max_acceleration: 0
  my_joint_b2:
    has_velocity_limits: true
    max_velocity: 4.01425739
    has_acceleration_limits: false
    max_acceleration: 0
  my_joint_e2:
    has_velocity_limits: true
    max_velocity: 3.4906586
    has_acceleration_limits: false
    max_acceleration: 0
  my_joint_l2:
    has_velocity_limits: true
    max_velocity: 3.4906586
    has_acceleration_limits: false
    max_acceleration: 0
  my_joint_r2:
    has_velocity_limits: true
    max_velocity: 3.4906586
    has_acceleration_limits: false
    max_acceleration: 0
  my_joint_s2:
    has_velocity_limits: true
    max_velocity: 3.4906586
    has_acceleration_limits: false
    max_acceleration: 0
  my_joint_t2:
    has_velocity_limits: true
    max_velocity: 6.10865255
    has_acceleration_limits: false
    max_acceleration: 0
  my_joint_u2:
    has_velocity_limits: true
    max_velocity: 3.4906586
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 0